name: 'Coverage'
on:
  pull_request:
    branches:
      - main
  push:
      branches:
        - main
jobs:
    coverage:
        runs-on: ubuntu-22.04
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.1'
              coverage: none

          - name: Install Node
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm

          - name: Install NPM Modules
            run: npm ci

          - name: Generate Coverage Report
            uses: ArtiomTr/jest-coverage-report-action@v2
            with:
              test-script: npm test
    badge:
        runs-on: ubuntu-22.04
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.1'
              coverage: none

          - name: Install Node
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: npm

          - name: Install NPM Modules
            run: npm ci

          - name: Run Tests with Coverage and Generate Badge
            run: |
               SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
               TOKENS=($SUMMARY)
               echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          - name: Create the Badge
            if: github.ref == 'refs/heads/main'
            uses: schneegans/dynamic-badges-action@v1.7.0
            with:
              auth: ${{ secrets.GIST_SECRET }}
              gistID: 973903d12880da1524ee6f9c9005ee23
              label: Coverage
              message: ${{ env.COVERAGE }}
              filename: coverage_badge.json
              color: green
              namedLogo: jest
              minColorRange: 90
              maxColorRange: 100

